# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# *** DEVELOPMENT ***
development:
  secret_key_base: 72326056f5969bc791d3ee1e00338190cd623c66a39580d5b641f0c8339b5359a3a5da71447c0d6d36ade8458d7c10551a266bd383863e4486aa1c7605b44bed

  # Store half your key in your codebase (DO NOT CHECK IN TO A PUBLIC REPO!)
  # and the other half in your env. This means an attacker needs access to both.
  code_encryption_key: '' # Insert half your key here, encoded in base64
  env_encryption_key: <%= ENV["ENCRYPTION_KEY"] %> # Other half in this env var, again in base64

  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

  # Not strictly a secret, but should be an env var so easier to keep all env vars here
  host: <%= ENV["HOST"] %>

# *** TEST ***
test:
  secret_key_base: 26318660c76acb57002ad5a40e44e20b99a787069d23f4f406c8bf1b875a64dbfda162bba6f68febf163e2a3dfb213eb3b6481ae9936af2edb778b26f7c2761a

  # Store half your key in your codebase (DO NOT CHECK IN TO A PUBLIC REPO!)
  # and the other half in your env. This means an attacker needs access to both.
  code_encryption_key: '' # Insert half your key here, encoded in base64
  env_encryption_key: <%= ENV["ENCRYPTION_KEY"] %> # Other half in this env var, again in base64

  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

  # Not strictly a secret, but should be an env var so easier to keep all env vars here
  host: <%= ENV["HOST"] %>

# *** PRODUCTION ***
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  # Store half your key in your codebase (DO NOT CHECK IN TO A PUBLIC REPO!)
  # and the other half in your env. This means an attacker needs access to both.
  code_encryption_key: '' # Insert half your key here, encoded in base64
  env_encryption_key: <%= ENV["ENCRYPTION_KEY"] %> # Other half in this env var, again in base64

  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

  # Not strictly a secret, but should be an env var so easier to keep all env vars here
  host: <%= ENV["HOST"] %>
